spring:
  config:
    activate:
      on-profile: qa

build:
  version: 2.0

loans:
  message: "Welcome to loan  related QA APIs "
  contactDetails:
    name: "Sneha Doe - QA Lead"
    email: "snehaD@svr.com"
  onCallSupport:
    - (555) 777-4568
    - (555) 666-9874
